#普通数据配置
name: develop

#对象的配置
#1
person:


  sex: male
#2.行内对象配置
#person: {name: 18,age: 20}

#数据、集合配置(字符串数据)
#1.
#city:
#  - beijing
#  - tianjin
#  - chongqing
#  - shanghai
#2.
#city: [beijing,tianjing,chongqing,shanghai]
#数据、集合配置(对象数据)
#1.
#person:
#  - name: tom
#    age: 20
#  - name: lucy
#    age: 23
#2.
#person: [{name: tom,age: 20},{name: lucy,age: 23}]

#Map配置(同上)


server:
  port: 8080
#  servlet:
#    context-path: /kylindev

#数据库链接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/filter?useUnicode=true&characterEncoding=utf8
    username: root
    password: root1234

#mybatis:
#  table:
#    auto: create # 自动建表模式，可选值有update（更新模式）、create（创建模式）等
#  model:
#    pack: com.collaborativefiltering.recommendationengine.model.auto # 扫描用于创建表的对象的包名
#  database:
#    type: mysql # 数据库类型，目前只支持mysql
#
#mybatis-plus:
#  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

#配置mybatis信息(配合xml使用)
#mybatis:
#  type-aliases-package: com.kylin.entity
#  mapper-locations: classpath*:mapper/*Mapper.xml
